Capstone/Controllers/BracketController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class BracketController : Controller
    {
        private TournamentManagerContext db = new TournamentManagerContext();

        //GET: Bracket/GetTournament/5
        public ActionResult Index(int? id)
        {
			
			ViewBag.Id = id.ToString();
            return View();
        }

        public JsonResult GetTournament(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Tournament tournament = db.Tournaments.Find(id);
            var tournamentTeams = db.Teams.Where(a => a.TournamentId == id).ToList();

            if (tournamentTeams == null)
            {
                //return HttpNotFound();
            }

            TourneyJSON output = new TourneyJSON();

            for (int i = 0; i < tournamentTeams.Count() - 1; i += 2)
            {
                string teamA = tournamentTeams[i].Name;
                var teamB = (tournamentTeams[i + 1].Name == null) ? null : tournamentTeams[i + 1].Name;

                output.teams.Add(new List<string>() { teamA, teamB });
            }

            return Json(output, JsonRequestBehavior.AllowGet);
        }
    }
}

Capstone/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using Microsoft.AspNet.Identity;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        //return View(await db.Tournaments.Where(a => a.OrganizerId == id).ToListAsync());
        //public ActionResult Index()
        //{
        //    if (User.Identity.IsAuthenticated == true)
        //    {
        //        return View("IndexSignedIn");
        //    }
        //    return View();
        //}

        private TournamentManagerContext db = new TournamentManagerContext();
        public async Task<ActionResult> Index()
        {
            var id = User.Identity.GetUserId();
            
            return View(await db.Tournaments.ToListAsync());

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            if (User.Identity.IsAuthenticated == true)
            {
                return View("AboutSignedIn");
            }

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            if (User.Identity.IsAuthenticated == true)
            {
                return View("ContactSignedIn");
            }

            return View();
        }
    }
}

Capstone/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>A Tech Elevator student capstone</h3>

<p>Good Boy is an application that aims to make managing your tournaments a little easier.</p>

Capstone/Views/Home/AboutSignedIn.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutSignedIn.cshtml";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Capstone/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    List<string> Contacts = new List<string>() { "jslucas", "bkeller", "joshmainini" };
}
<h2>@ViewBag.Title.</h2>
<h3>Find us on GitHub</h3>

@{ 
    foreach(string contact in Contacts)
    {
        <p><a href="https://github.com/@contact">@@@contact</a></p>
    }
}

Capstone/Views/Home/ContactSignedIn.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutSignedIn.cshtml";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Capstone/Views/Home/Index.cshtml
@using WebApplication1.Models;

@model IEnumerable<WebApplication1.Models.Tournament>
@{
    ViewBag.Title = "Home Page";

}

@section scripts {
    <link rel="stylesheet" type="text/css" href="~/Content/homeindex.css" />
}

<div class="jumbotron">
    <h1>It's gonna be huge</h1>
    <p class="lead">We gonna finish it</p>

</div>

<div class="row">
    <div class="col-md-4 scroll">
        <h2>Active Tournaments</h2>
        <table class="table">
            @{
                foreach (var item in Model)
                {
                    if (item.Start < DateTime.Now && item.End > DateTime.Now)
                    {
                        <tr>
                            <td>
                                @{
                                    string name = item.Name;
                                }
                                @Html.ActionLink(name, "Index", "Bracket", new { id = item.TournamentId }, null)
                            </td>
                        </tr>
                                        }

                                    }
            }
        </table>

        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4 scroll">
        <h2>Past Tournaments</h2>
        <table class="table">
            @{
                foreach (var item in Model)
                {
                    if (item.End < DateTime.Now)
                    {
                        <tr>
                            <td>
                                @{
                                    string name = item.Name;
                                }
                                @Html.ActionLink(name, "Index", "Bracket", new { id = item.TournamentId }, null)
                            </td>
                        </tr>
                                        }
                                    }
            }
        </table>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>

    <div class="col-md-4 scroll">
        <h2>Upcoming Tournaments</h2>
        <table class="table">
            @{
                foreach (var item in Model)
                {
                    if (item.Start > DateTime.Now)
                    {
                        <tr>
                            <td>
                                @{
                                    string name = item.Name;
                                }
                                @Html.ActionLink(name, "Index", "Bracket", new { id = item.TournamentId }, null)
                            </td>
                        </tr>
                                        }
                                    }
            }
        </table>

        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>

Capstone/Views/Home/IndexSignedIn.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_LayoutSignedIn.cshtml";
}

<div class="jumbotron">
    <h1>It's gonna be huge</h1>
    <p class="lead">We gonna finish it</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>